#!/usr/bin/env bash

folder_name=$1
echo Moving all the results into $folder_name ... 

if ! ls surface_eps_*.dat 1> /dev/null 2>&1; then
    echo "Error: no surface files (surface_eps_*.dat) were generated by MUSIC."
    exit 1
fi

# combine multiple surface files
for ii in `ls surface_eps_*.dat`
do 
    echo $ii
    jj=`echo $ii | cut -f 1-2 -d _ `
    cat $ii >> $jj.dat
done
rm surface_eps_*.dat 2> /dev/null

mkdir $folder_name
mv *.dat $folder_name
mv *.err $folder_name 2>/dev/null
mv *.log $folder_name
cp music_input_mode_2 $folder_name/music_input

echo "sweeper.sh ran correctly" 
